import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios  from 'axios'
import Link from 'next/link'
import { useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

export default function DashBoard({user}) {
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div style={{textAlign:'center'}}>
    <h1>Welcome {user.name} </h1>
    <div className='dashboard-container'>
      <h3>Upload Files</h3>
      <Link href="/" >Go to Home</Link>
      <h3>Your Uploaded Files</h3>
      </div>
      <div className='dashboarditems' style={{display:'flex',flexWrap:'wrap',justifyContent:'center',gap:'15px',textAlign:'center'}}>
      {user.uploadedFiles.map((item)=>{
          return(<div className='cheatsheet' style={{width:'200px',height:'300px',padding:'20px',boxShadow:'10px 10px' ,backgroundColor:'#ccccff'}}>
           <h3 style={{border:'2px solid black'}}>{item.name}</h3>
           <a href={item.link} style={{padding:'9px', background:'black', color:'white',textDecoration:'none'}} >Download</a>
            <h4>Price:{item.price}</h4>
           <p>{item.category}</p>
           <p>Created By {item.author}</p>
           {item.verified==="yes"?<p style={{color:'green'}}>verified</p>:<p style={{color:'red'}}>Not verified</p>}
          </div>)
        })}
        </div>

    </div>
  </div>
    </>
  )
}

function UploadForm(){
  return(
    <>
    <div>
      
    </div>
    </>
  )
}

export async function getServerSideProps({ query }) {
  //const { user } = query;
  try {
    const { userid } = query;
    //const response = await axios.get('https://sharenote-api.onrender.com/allFiles');
    const response= await axios.get(`https://sharenote-api.onrender.com/user/${userid}`)
    const user = response.data;
   
    return {
      props: {
        
        user
        
      },
    };
  } catch (error) {
    console.log(error);
    return {
      props: {
       
        user:{},
       
      },
    };
  }
}

// export async function getStaticProps({query}){
//   let data;
//   const {user} =query;
//   axios.get('https://sharenote-api.onrender.com/allFiles')
//   .then((response) => {
//     //setData(response.data);
//     data=response.data
//   })
//   .catch((error) => console.log(error));
//   return {
//     props:{
//       user:user,
//       data:data
//     }
//   }
// }

