import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios  from 'axios'
import Link from 'next/link'
import { useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

export default function DashBoard({user}) {
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
    <h1>Welcome {user.name} </h1>
    <div className='dashboard-container'>
      <h3>Upload Files</h3>
      <Link href='/'>Go to Home</Link>
      
      <h3>Your Uploaded Files</h3>
      <div className='dashboard-items' style={{display:'flex',flexWrap:'wrap'}}>
      {user.uploadedFiles.map((item)=>{
          return(<div className='cheat-sheet'>
           <h3>{item.name}</h3>
           <a href={item.link} >Download</a>
          <h4>Price:{item.price}</h4>
           <p>{item.category}</p>
           <p>Created By {item.author}</p>
      
           {item.verified==="yes"?<p style={{color:'green'}}>verified</p>:<p style={{color:'red'}}>Not verified</p>}
          </div>)
        })}
        </div>

    </div>
  </div>
    </>
  )
}

export async function getServerSideProps({ query }) {
  //const { user } = query;
  try {
    const { user } = query;
    const response = await axios.get('https://sharenote-api.onrender.com/allFiles');
    const res= await axios.get(`https://sharenote-api.onrender.com/user/${user}`)
    const data = response.data;
    const userdetails=res.data
    return {
      props: {
        data,
        user,
        userdetails
      },
    };
  } catch (error) {
    console.log(error);
    return {
      props: {
        data: [],
        user:'Please Sign In',
        userdetails:'none'
      },
    };
  }
}

// export async function getStaticProps({query}){
//   let data;
//   const {user} =query;
//   axios.get('https://sharenote-api.onrender.com/allFiles')
//   .then((response) => {
//     //setData(response.data);
//     data=response.data
//   })
//   .catch((error) => console.log(error));
//   return {
//     props:{
//       user:user,
//       data:data
//     }
//   }
// }

