import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios  from 'axios'
import Link from 'next/link'
import { useState } from 'react'
const inter = Inter({ subsets: ['latin'] })
//import firebase from 'firebase'
export default function DashBoard({user}) {
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div >
        <div style={{textAlign:'center'}}>
    <h1>Welcome {user.name} </h1>
    <div className='dashboard-container' style={{}} >
      <h3>Upload Files</h3>
      <UploadForm userid={user._id} />
      <Link href="/" >Go to Home</Link>
      <h3>Your Uploaded Files</h3>
      </div>
      <div className='dashboarditems' style={{display:'flex',flexWrap:'wrap',justifyContent:'center',gap:'15px',textAlign:'center'}}>
      {user.uploadedFiles.map((item)=>{
          return(<div className='cheatsheet' style={{width:'200px',height:'300px',padding:'20px',boxShadow:'10px 10px' ,backgroundColor:'#ccccff'}}>
           <h3 style={{border:'2px solid black'}}>{item.name}</h3>
           <a href={item.link} style={{padding:'9px', background:'black', color:'white',textDecoration:'none'}} >Download</a>
            <h4>Price:{item.price}</h4>
           <p>{item.category}</p>
           <p>Created By {item.author}</p>
           {item.verified==="yes"?<p style={{color:'green'}}>verified</p>:<p style={{color:'red'}}>Not verified</p>}
          </div>)
        })}
        </div>

    </div>
  </div>
    </>
  )
}

function UploadForm({userid}){
  const [name, setName] = useState('');
  const [category, setCategory] = useState('');
  const [link, setLink] = useState('');
  const [price, setPrice] = useState('');
  const handleSubmit = (event) => {
    event.preventDefault();
    axios.post(`https://sharenote-api.onrender.com/uploadFiles/${userid}`, {
      name,
      category,
      link,
      price,
    })
      .then((response) => {
      //  console.log(response);
        // Handle successful response here
        if(response.data.message==='File uploaded successfully'){
          alert("File Uploadeed Succesfully")
          

        }
      })
      .catch((error) => {
        console.error(error);
        alert("errot",error)
        // Handle error response here
      });
  };

  return(
    <>
    <div style={{padding:'30px',background:'#b3d9ff',boxShadow: '0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)',width:'20em',display:'flex',justifyContent:'center',margin:'auto'}}>
    <form onSubmit={handleSubmit} className="upload-form" style={{display:'flex',flexDirection:'column',gap:'20px',justifyContent:'center'}}>
      <label htmlFor="name">Name:</label>
      <input
        type="text"
        id="name"
        value={name}
        onChange={(event) => setName(event.target.value)}
        style={{width:'300px',height:'30px'}}
        className="form-input"
      />

      <label htmlFor="category">Category:</label>
      <input
        type="text"
        id="category"
        style={{width:'300px',height:'30px'}}
        value={category}
        onChange={(event) => setCategory(event.target.value)}
        className="form-input"
      />

      <label htmlFor="link">Link:</label>
      <input
        type="text"
        id="link"
        style={{width:'300px',height:'30px'}}
        value={link}
        onChange={(event) => setLink(event.target.value)}
        className="form-input"
      />

      <label htmlFor="price">Price:</label>
      <input
        type="text"
        id="price"
        style={{width:'300px',height:'30px'}}
        value={price}
        onChange={(event) => setPrice(event.target.value)}
        className="form-input"
      />

      <button type="submit" className="form-submit-button" style={{padding:'9px', background:'black', color:'white',textDecoration:'none'}}>Upload File</button>
    </form>
    </div>
    </>
  )
}

export async function getServerSideProps({ query }) {
  //const { user } = query;
  try {
    const { userid } = query;
    //const response = await axios.get('https://sharenote-api.onrender.com/allFiles');
    const response= await axios.get(`https://sharenote-api.onrender.com/user/${userid}`)
    const user = response.data;
   
    return {
      props: {
        
        user
        
      },
    };
  } catch (error) {
    console.log(error);
    return {
      props: {
       
        user:{},
       
      },
    };
  }
}

// export async function getStaticProps({query}){
//   let data;
//   const {user} =query;
//   axios.get('https://sharenote-api.onrender.com/allFiles')
//   .then((response) => {
//     //setData(response.data);
//     data=response.data
//   })
//   .catch((error) => console.log(error));
//   return {
//     props:{
//       user:user,
//       data:data
//     }
//   }
// }

