import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios  from 'axios'
import Link from 'next/link'
import { useState } from 'react'
import { useRouter } from 'next/router'
const inter = Inter({ subsets: ['latin'] })

export default function File({item}) {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div style={{display:'flex',flexDirection:'column',gap:'1em',justifyItems:'center',width:'100%'}}>
<div style={{background:'#ccccff',padding:'30px',width:'30em'}}>
    <h4>{item.name}</h4>
    <h3>Price:{item.price}<br/>verified:{item.verified}</h3>
    <h3>Uploaded by {item.author}</h3>
    <h3>Category   {item.category}</h3>
    <a href={item.link}>Download</a>
</div>
       <div><iframe src={item.link} title={item.name} style={{width:'40rem',height:'50rem'}}></iframe>
       </div> 
        </div>
    </>
  )
}

export async function getServerSideProps({ query }) {
  
    
    const item=JSON.parse(query.ItemObject)
   // let data = [];
  
   return {props:{
     item
   }}
}


