import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/file.module.css'
import axios  from 'axios'
import Link from 'next/link'
import { useState } from 'react'
import { useRouter } from 'next/router'


export default function File({item}) {
  const url="https://cdn.pixabay.com/photo/2016/12/07/15/57/blur-1889747_1280.jpg"

  const [islogin,setLogin]=useState(false)

  const [showpop,setShowpop]=useState(false)
  return (
    <>
      <Head>
        <title>PustakSathi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
     <div  className="bg-gray-100">
    {/* <div style={{background:'white',padding:'30px',width:'20em',fontFamily:'sans-serif,roboto',textAlign:'center',borderRadius:'1px',boxShadow:'0 0 5px rgba(0, 0, 0, 0.5)'}}>
    <h2>{item.name}</h2>
    <h3>Price:{item.price}<br/>verified:{item.verified}</h3>
    <h3>Uploaded by {item.author}</h3>
    <h3>Category   {item.category}</h3>
    <div style={{display:'flex',flexDirection:'column',gap:'10'}}>
   {!islogin && <button  onClick={()=>{ setShowpop(true) }} style={{padding:'20px',textDecoration:'none',backgroundColor:'black',color:'white',fontSize:'1.2em'}}>Register</button> }
    {showpop && <Popup islogin={islogin} setLogin={setLogin} setShowpop={setShowpop} showpop={showpop}  />}
    {islogin && <a href={item.link} style={{padding:'10px',textDecoration:'none',backgroundColor:'black',color:'white'}} >Download</a>}
    </div>
</div> */}
   <div className='flex flex-wrap p-1  h-50 m-auto'>
    <div className='lg:p-10 lg:m-10 md:p-9  p-10  m-auto shadow '>
     <img className='w-40 h-60 shadow ' src='https://th.bing.com/th/id/R.855e8ca01684f0d61e302ba09a177bfd?rik=TbKuqNR1U%2bV6Iw&riu=http%3a%2f%2fwww.fremontgurdwara.org%2fwp-content%2fuploads%2f2020%2f06%2fno-image-icon-2.png&ehk=CSKwfMp5gN3Q7qhs6urcmM7WX1EHsd%2f3sCS8jJu8lRU%3d&risl=&pid=ImgRaw&r=0'/>
    </div>
    <div className='p-10 text-center font-mono'>
    <h1 className='text-2xl m-4'>{item.name}</h1>
    <h1 className='text-2xl  m-4'>Uploaded By {item.author}</h1>
    <h2 className='text-2xl  m-4'>Price: {item.price}</h2>
    <h2 className='text-2xl  m-4'>Category {item.category}</h2>
    <button className='border-black border-2 p-2 w-60   m-4 hover:shadow-lg'>Preview</button><br/>
    <a className=' px-20 text-white m-4 bg-black py-3 hover:shadow-lg'  href={item.link}>Download</a>

    </div>
   </div>
       
        </div>
         <div>
          <h1 className='text-3xl text-center font-mono'>Reviews</h1>
               
        </div>
    </>
  )
}

function Popup({islogin,setLogin,setShowpop,showpop}) {
  
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleRegister = () => {
    // handle registration logic
    axios.post('https://sharenote-api.onrender.com/registerUser', {
      name: name,
      email: email,
      password: password
    }).then((response) => {
      console.log(response.data)
      if(response.data.msg==="Inserted"){
        setLogin(true);
        setShowpop(false)
      }
    }).catch(error => {
      alert("Unable to register",error);
      console.log(error);
    });
  };

  const handleLogin = () => {
    // handle login logic
    axios.post('https://sharenote-api.onrender.com/loginUser', {
      email: email,
      password: password
    }).then(response => {
      console.log(response.data)
      if(response.data.message==="User logged in successfully"){
        setLogin(true);
        setShowpop(false)
      }
    }).catch(error => {
      alert("Unable to login",error);
      console.log(error);
    });
  };

  return (
    <div style={{ position: 'fixed', top: 0, left: 0, width: '100%', height: '100%', backgroundColor: 'rgba(0, 0, 0, 0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <div style={{ backgroundColor: 'white', padding: '20px', borderRadius: '5px', boxShadow: '0 0 10px rgba(0, 0, 0, 0.2)', maxWidth: '400px' }}>
      
          <div style={{display:'flex',flexDirection:'column'}}>
            <h2 className='text-3xl font-bold underline'>Register</h2>
            <label>Name:</label>
            <input type="text" value={name} onChange={(e) => setName(e.target.value)} />
            <br />
            <label>Email:</label>
            <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} />
            <br />
            <label>Password:</label>
            <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
            <br />
            <button onClick={handleRegister} className="bg-blue">Register</button>
          </div>
          <div style={{display:'flex',flexDirection:'column'}}>
            <h2>Login</h2>
            <label >Email:</label>
            <input type="email" onChange={(e)=>{setEmail(e.target.value)}} />
            <br />
            <label>Password:</label>
            <input type="password" onChange={(e)=>{setPassword(e.target.value)}}  />
            <br />
            <button onClick={handleLogin}>Login</button>
            
          </div>
        
      </div>
    </div>
  );
}


export async function getServerSideProps({ query }) {
  
    
    const item=JSON.parse(query.ItemObject)
    const login =query
   // let data = [];
  
   return {props:{
     item,
     login
   }}
}


