import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios  from 'axios'
import Link from 'next/link'
import { useState } from 'react'
import { useRouter } from 'next/router'
const inter = Inter({ subsets: ['latin'] })

export default function Home({user,data,userdetails}) {
  const router=useRouter
  const shareData = {
    title: '',
    text: 'Check out this link:',
    url: '',
  };
  const share = async () => {
    try {
      await navigator.share(shareData);
     
    } catch (error) {
     console.log(error)
    }
  };
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.head}>
      <h1 className={styles.h1}>Welcome to ShareYourNotes</h1>
      { userdetails && <h3>Welcome {userdetails.name}</h3> }
        <h3 className={styles.h3}>CheatSheets and notes available currently<br/>
        Please Fill This Form <a href='https://docs.google.com/forms/d/e/1FAIpQLSeCsgCXWN4r_c4lrdlAv1suFWBeKw_krgNu5WaUFJ0l0Fvc7Q/viewform?usp=sf_link'>Link</a>
       </h3>
       <button onClick={()=>{
         router.push({
          pathname: '/dashboard',
          query: { user:userdetails},
         })
        }} style={{ backgroundColor: '#4285f4', color: '#fff', fontSize: '1.1rem', padding: '0.5rem 1rem', borderRadius: '5px', border: 'none', cursor: 'pointer' }} >Go to DashBoard</button>
       <p className={styles.p} id="blink" style={{animation:'blink 2s linear infinite'}}>After Clicking Download Link Please Request Access Permission .You may have to wait to get permission as its a manual process</p>
       </div>
      <div className={styles.App}>
       <div className={styles.cheatsheetcontainer}>
        {data.map((item)=>{
          return(<div className={styles.cheatsheet}>
           <h3 className={styles.h3}>{item.name}</h3>
           {shareData.text=item.name}
           <a href={item.link} className={styles.a} >Download</a>
           <button id='share' onClick={share} className={styles.button}>Share</button>
          <h4 className={styles.h4}>Price:{item.price}</h4>
           <p className={styles.p}>{item.category}</p>
           <p className={styles.p}>Created By {item.author}</p>
      
           {item.verified==="yes"?<p style={{color:'green'}} className={styles.p}>verified</p>:<p style={{color:'red'}} className={styles.p}>Not verified</p>}
          </div>)
        })}
       </div>
      

    </div>
    </>
  )
}

export async function getServerSideProps({ query }) {
  //const { user } = query;
  try {
    const { user } = query;
    const response = await axios.get('https://sharenote-api.onrender.com/allFiles');
    const res= await axios.get(`https://sharenote-api.onrender.com/user/${user}`)
    const data = response.data;
    const userdetails=res.data
    return {
      props: {
        data,
        user,
        userdetails
      },
    };
  } catch (error) {
    console.log(error);
    return {
      props: {
        data: [],
        user:'Please Sign In',
        userdetails:'none'
      },
    };
  }
}

// export async function getStaticProps({query}){
//   let data;
//   const {user} =query;
//   axios.get('https://sharenote-api.onrender.com/allFiles')
//   .then((response) => {
//     //setData(response.data);
//     data=response.data
//   })
//   .catch((error) => console.log(error));
//   return {
//     props:{
//       user:user,
//       data:data
//     }
//   }
// }

