import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Login.module.css'
import axios  from 'axios'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function LogIn() {

  const [email, setEmail] = useState('');
  //const [route,setRoute]=useState('login')
  const [password, setPassword] = useState('');
  const router = useRouter();

  const handleSubmit = (event) => {
    event.preventDefault();
    console.log(email,password);
    // Here you can make an Axios POST request to submit the form data
    // axios.post('https://sharenote-api.onrender.com/loginUser', {
    //   email,
    //   password,
    // })
    //   .then((response) => {
       
    //     // Handle successful response here
    //     console.log(response)
    //     if(response.data.message==="User logged in successfully"){
        
    //       console.log(response.data.user)
          
    //     }
    //   })
    //   .catch((error) => {
    //     console.error(error);
    //     // Handle error response here
    //   });

    fetch('https://sharenote-api.onrender.com/loginUser', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        email,
        password,
      })
    })
      .then((response) => {
        return response.json();
      })
      .then((data) => {
        console.log(data);
        if (data.message === "User logged in successfully") {
          console.log(data.user);
          router.push({
            pathname: '/',
            query: { user:data.user._id },
          });
        }
      })
      .catch((error) => {
        console.error(error);
        // Handle error response here
      });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.h1}>Welcome to ShareYourNotes</h1>
      <div className={styles.LoginForm}>
   <div>
      <form onSubmit={handleSubmit} className={styles.form}>
        <label htmlFor="email" className={styles.label}>Email:</label>
        <input
          type="email"
          id="email"
          value={email}
          className={styles.input}
          onChange={(event) => setEmail(event.target.value)}
        />

       

        <label htmlFor="password" className={styles.label}>Password:</label>
        <input
          type="password"
          id="password"
          value={password}
          className={styles.input}
          onChange={(event) => setPassword(event.target.value)}
        />

        <button type="submit" style={{ backgroundColor: '#4285f4', color: '#fff', fontSize: '1.1rem', padding: '0.5rem 1rem', borderRadius: '5px', border: 'none', cursor: 'pointer' }}   >Submit</button>
      </form>
      <button onClick={()=>{console.log('hello')}  }  className={styles.button} style={{ backgroundColor: '#4285f4', color: '#fff', fontSize: '1.1rem', padding: '0.5rem 1rem', borderRadius: '5px', border: 'none', cursor: 'pointer' }}          >Register Here</button>
      </div>

    </div>
    </>
  )
}

