import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/file.module.css'
import axios  from 'axios'
import Link from 'next/link'
import { useState } from 'react'
import { useRouter } from 'next/router'


export default function Profile({user}) {
  //const url="https://cdn.pixabay.com/photo/2016/12/07/15/57/blur-1889747_1280.jpg"
  const [islogin,setLogin]=useState(false)
  const [showpop,setShowpop]=useState(false)
  return (
    <>
      <Head>
        <title>PustakSathi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
    <div>
        <div>
        <img/>
        <h1>{user.name}</h1>
        </div>
        <div>

        </div>
     </div>
    

    </>
  )
}



export async function getServerSideProps({ query }) {
  
    
    const user=JSON.parse(query.user)
    
   // let data = [];
  
   return {props:{
     user
   }}
}


