import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Login.module.css'
import axios  from 'axios'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useState } from 'react'



export default function LogIn() {

  const [email, setEmail] = useState('');
  const [name,setName]=useState('')
  const [show,setShow]=useState(false)
  const [password, setPassword] = useState('');
  const router = useRouter();

  const handleSubmit = (event) => {
    event.preventDefault();
    console.log(email,password);
      setShow('Please Wait....')
    fetch('https://sharenote-api.onrender.com/registerUser', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name,
        email,
        password,
      })
    })
      .then((response) => {
        return response.json();
      })
      .then((data) => {
        console.log(data);
        if (data.msg === "Inserted") {
          console.log(data.user);
          router.push({
            pathname: '/',
            query: { user:data.user._id },
          });
        }
      })
      .catch((error) => {
        console.error(error);
        // Handle error response here
      });
  };

  return (
    <>
      <Head>
        <title>PustakSathi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/logo.png" />
      </Head>
      <h1 className={styles.h1}>PustakSathi</h1>
      <h3>{show}</h3>
      <div className={styles.LoginForm}>
      <Image src="/images/logo.png" width='100' height='100' />
   <div>
      <form onSubmit={handleSubmit} className={styles.form}>
      <label htmlFor="name" className={styles.label}>Name:</label>
        <input
          type="text"
          id="text"
          value={name}
          className={styles.input}
          onChange={(event) => setName(event.target.value)}
        />
        <label htmlFor="email" className={styles.label}>Email:</label>
        <input
          type="email"
          id="email"
          value={email}
          className={styles.input}
          onChange={(event) => setEmail(event.target.value)}
        />

       

        <label htmlFor="password" className={styles.label}>Password:</label>
        <input
          type="password"
          id="password"
          value={password}
          className={styles.input}
          onChange={(event) => setPassword(event.target.value)}
        />

        <button type="submit" style={{ backgroundColor: '#4285f4', color: '#fff', fontSize: '1.1rem', padding: '0.5rem 1rem', borderRadius: '5px', border: 'none', cursor: 'pointer' }}   >Submit</button>
      </form>
      <button onClick={()=>{console.log('hello')}  }  className={styles.button} style={{ backgroundColor: '#4285f4', color: '#fff', fontSize: '1.1rem', padding: '0.5rem 1rem', borderRadius: '5px', border: 'none', cursor: 'pointer' }}><Link href="/login">Login Here</Link></button>
      </div>

    </div>
    </>
  )
}

